[build]
  base = "."
  command = "npm run build"
  publish = "dist"

[headers]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  Referrer-Policy = "no-referrer"
  X-Content-Type-Options = "nosniff"
  Permissions-Policy = "geolocation=(), microphone=()"
  Content-Security-Policy = "upgrade-insecure-requests"
  X-Permitted-Cross-Domain-Policies = "none"

[redirects]
  "/c" = "https://github.com/ChrisTitusTech/winutil"
  "/mas" = "https://github.com/massgravel/Microsoft-Activation-Scripts"
